upstream accountService{
    server account-service:8080;
}

upstream customerService{
    server customer-service:8080;
}

upstream interventionService{
    server intervention-service:8080;
}

upstream relationService{
    server relation-service:8080;
}

upstream documentService{
    server document-service:8080;
}

server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    location ~ ^/account/([^/]+)/moveNextPhase {
            proxy_pass http://accountService/accounts/$1/moveNextPhase;
    }

    location /account {
       proxy_pass http://accountService/accounts;
    }

    location /customer/intervention {
            proxy_pass http://customerService/customers/intervention;
    }

    location /customer/relation {
            proxy_pass http://customerService/customers/relation;
    }

    location ~ ^/customer/([^/]+) {
           proxy_pass http://customerService/customers/$1;
    }

    location /customer {
           proxy_pass http://customerService/customers;
    }

    location /intervention {
           proxy_pass http://interventionService/interventions;
    }

    location /relation {
           proxy_pass http://relationService/relations;
    }

    location /document {
           proxy_pass http://documentService/documents;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}